baseURL = "https://b-rc.cl/"
languageCode = "es-cl"
title = "BRC 2022"


theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true


# Todo eso va en los metadatos, hay que llenarlo bien bien
[params]
    title = "BRC 2022 :heart: "
    date = "2022-08-09"
    description = "Beauchef Robotics Challenge es la competencia de robótica de la FCFM que reúne a escolares, estudiantes de universidad y profesionales en torno al aprendizaje y desarrollo de competencias en electrónica, fabricación digital y programación. "
    images = ["/images/social-share.jpg"]
    email = "beauchefrc@gmail.com"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = "We :heart:️ robocs"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#ff0000"